version: '3'
networks:
  my-network:
    driver: bridge
services:
  web_api:
    image: ricardogaefke/profile4d:web_api_cloud
    container_name: web-api
    networks:
      - my-network
    env_file: ./docker-compose.env
  nginx:
    image: nginx_dev
    container_name: nginx-proxy
    ports:
      - "5065:8080"
    networks:
      - my-network
